### PR TITLE
Add Python script to generate the JSON data from XML data

### PR DESCRIPTION
**Pull request by misspellted**
I saw that the XML data was relatively simple in structure, so I added a JSON adapter from the XML data file.

As noted in the updated README, the JSON data file can be generated by running the Python script codes.py, which will overwrite the codes.json file.

I'm open to any remarks, and of course, suggestions for improvements, especially revolving around the ```test()``` method, which isn't quite really a good test (since it has to be run from within the interpreter, and it doesn't indicate any failures or success, like a unit test [suite] would).

### CODE REVIEW

**Comment by Altenius** [comment]
This looks good to me but the only thing I would change is making the json data a map like:
```json
{
    "codes": {
        "P1000": "Example code"
    }
}
```
to make accessing specific codes easier.
The `test()` method looks fine to me; there's not much we can do with unit testing here.

**Comment by misspellted** [comment]
Thanks for the comments!

I'll get to work on making that change for the JSON data.

**Comment by misspellted** [comment]
Actually, I'm not sure the codes array can be composed exactly like that.

The JSON array is composed of objects, each having the squiggly braces around the code and the text, which would look something like:
```
{
    "codes": [
        {
            "P1000": "Example code"
        },
        {
        }
    ]
}
```

Another option would be to have an unnamed array:
```
[
    {
        "P1000": "Example code"
    },
    {
    }
]
```

**Comment by misspellted** [comment]
Furthermore, a third alternative would be to just have one object with a lot of fields:
```
{
    "P1000": "Example code",
    "...": "..."
}
```

---

In looking into the possibility of the above alternative, I decided to incorporate all current options, and therefore, my impending changes will have 5 methods available. I'll get to updating the PR shortly.

**Comment by misspellted** [comment]
I've added the updated changes, which includes changing the generated JSON data to be in the "Unnamed Array/Verbose" structure. Of course, individual or project-based needs/desires can be different, so that is why there are 5 methods available, with the ability to introduce additional generated structured data as deemed by the user.

After adding the "All the Fields" structure, I realize I can just name that object as "codes", to make it look like the requested structure. I've been thinking of it as a list of codes, but I can see it as "All the Fields" too, so naming that object is simple. I'll make one last update, to get the requested structure.

**Comment by misspellted** [comment]
Alright, I'll stop making changes, let you look over the newer codes.json so you can let me know what you think.

**Comment by Altenius** [comment]
The changes look great so far, I'll rebase and merge after I'm done looking over it.

**Comment by misspellted** [comment]
I can't think of anything else to add at the moment.

**Pull request merged**
